
[workers]
imap = 4

[api]
maxSize = "5M" # maximum size of an attachment when submitting or uploading messages

[dbs]
# redis connection
redis = "rediss://default:e06fk2ek4qyniu6y@db-redis-lon1-52698-do-user-7389267-0.b.db.ondigitalocean.com:25061"

[log]
level = "trace"
